package main

import (
	"bufio"
	"context"
	"crypto/tls"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"math/rand"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"syscall"
	"time"
)

// Global state for verified "green" proxies
var (
	activeProxyPool []string
	poolMutex       sync.RWMutex
	activeWorkers   int64
	totalRequests   int64
)

type LocalProxyConfig struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Country  string `json:"country"`
	City     string `json:"city"`
	Server   string `json:"server"`
	Username string `json:"username"`
	Password string `json:"password"`
}

// fetchPublicProxies reads proxy endpoints from proxies.txt or json files
func fetchPublicProxies(txtPath, jsonPath string) []string {
	var harvestedList []string

	// 1. Read from shared proxies.txt (generated by Python scraper)
	if file, err := os.Open(txtPath); err == nil {
		scanner := bufio.NewScanner(file)
		count := 0
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line != "" && !strings.HasPrefix(line, "#") {
				if !strings.HasPrefix(line, "http://") && !strings.HasPrefix(line, "https://") {
					line = "http://" + line
				}
				harvestedList = append(harvestedList, line)
				count++
			}
		}
		file.Close()
		fmt.Printf("[Go Engine] Loaded %d raw proxies from %s\n", count, txtPath)
	}

	// 2. Also load any authenticated local residential proxies from JSON if present
	if data, err := os.ReadFile(jsonPath); err == nil {
		var localProxies []LocalProxyConfig
		if err := json.Unmarshal(data, &localProxies); err == nil {
			for _, lp := range localProxies {
				if lp.Server != "" {
					server := lp.Server
					if !strings.HasPrefix(server, "http://") && !strings.HasPrefix(server, "https://") {
						server = "http://" + server
					}
					if lp.Username != "" && lp.Password != "" {
						u, err := url.Parse(server)
						if err == nil {
							u.User = url.UserPassword(lp.Username, lp.Password)
							harvestedList = append(harvestedList, u.String())
							continue
						}
					}
					harvestedList = append(harvestedList, server)
				}
			}
		}
	}

	return harvestedList
}

// testAndFilterProxies runs health checks with a strict timeout to find responsive proxies
func testAndFilterProxies(rawProxies []string, targetTestURL string, maxTested int) {
	fmt.Printf("[Tester] Testing proxy health against: %s (limit: %d)...\n", targetTestURL, maxTested)
	var wg sync.WaitGroup
	semaphore := make(chan struct{}, 80) // Concurrency control

	var greenList []string
	var localMutex sync.Mutex

	tested := 0
	for _, pStr := range rawProxies {
		if maxTested > 0 && tested >= maxTested {
			break
		}
		tested++

		wg.Add(1)
		semaphore <- struct{}{}

		go func(proxyStr string) {
			defer wg.Done()
			defer func() { <-semaphore }()

			proxyURL, err := url.Parse(proxyStr)
			if err != nil {
				return
			}

			client := &http.Client{
				Transport: &http.Transport{
					Proxy:           http.ProxyURL(proxyURL),
					TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
				},
				Timeout: 4 * time.Second, // 4-second timeout filter
			}

			req, err := http.NewRequest("GET", targetTestURL, nil)
			if err != nil {
				return
			}
			req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")

			resp, err := client.Do(req)
			if err != nil {
				return // Unresponsive proxy dropped
			}
			resp.Body.Close()

			if resp.StatusCode >= 200 && resp.StatusCode < 400 {
				localMutex.Lock()
				greenList = append(greenList, proxyStr)
				localMutex.Unlock()
				fmt.Printf("  [💚 GREEN] Active Proxy: %s\n", proxyStr)
			}
		}(pStr)
	}

	wg.Wait()

	// Atomically swap the active pool with fresh verified proxies
	poolMutex.Lock()
	if len(greenList) > 0 {
		activeProxyPool = greenList
	}
	poolSize := len(activeProxyPool)
	poolMutex.Unlock()

	fmt.Printf("[System] ✅ Health checks complete. Active green pool: %d proxies.\n\n", poolSize)
}

// getRandomProxy safely retrieves a random proxy from the verified pool
func getRandomProxy() (string, error) {
	poolMutex.RLock()
	defer poolMutex.RUnlock()

	if len(activeProxyPool) == 0 {
		return "", fmt.Errorf("no active proxies available in pool")
	}

	return activeProxyPool[rand.Intn(len(activeProxyPool))], nil
}

// runTrafficSimulation manages worker connection cycles with automatic proxy rotation
func runTrafficSimulation(ctx context.Context, workerID int, targetURL string, wg *sync.WaitGroup) {
	defer wg.Done()
	atomic.AddInt64(&activeWorkers, 1)
	defer atomic.AddInt64(&activeWorkers, -1)

	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		proxyStr, err := getRandomProxy()
		if err != nil {
			time.Sleep(2 * time.Second)
			continue
		}

		proxyURL, err := url.Parse(proxyStr)
		if err != nil {
			continue
		}

		client := &http.Client{
			Transport: &http.Transport{
				Proxy:               http.ProxyURL(proxyURL),
				TLSClientConfig:     &tls.Config{InsecureSkipVerify: true},
				MaxIdleConns:        10,
				IdleConnTimeout:     30 * time.Second,
				DisableCompression:  false,
			},
			Timeout: 8 * time.Second,
		}

		req, err := http.NewRequestWithContext(ctx, "GET", targetURL, nil)
		if err != nil {
			continue
		}

		req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
		req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
		req.Header.Set("Accept-Language", "en-US,en;q=0.9")

		resp, err := client.Do(req)
		if err != nil {
			// Proxy dropped or timed out; cycle to another proxy immediately
			time.Sleep(500 * time.Millisecond)
			continue
		}

		// Close connection immediately to conserve bandwidth
		io.Copy(io.Discard, resp.Body)
		resp.Body.Close()

		reqCount := atomic.AddInt64(&totalRequests, 1)
		currentActive := atomic.LoadInt64(&activeWorkers)
		if reqCount%10 == 0 || reqCount <= 5 {
			fmt.Printf("[Worker #%03d] 🟢 Request completed via %s | Total Hits: %d | Active Workers: %d\n", workerID, proxyURL.Host, reqCount, currentActive)
		}

		select {
		case <-ctx.Done():
			return
		case <-time.After(time.Duration(2000+rand.Intn(3000)) * time.Millisecond):
		}
	}
}

func main() {
	targetURLFlag := flag.String("url", "https://httpbin.org/ip", "Target URL to query")
	channelFlag := flag.String("channel", "", "Optional channel name to query")
	workersFlag := flag.Int("workers", 20, "Number of concurrent worker goroutines")
	proxyTxtFlag := flag.String("proxies", "proxies.txt", "Path to proxies.txt")
	proxyJSONFlag := flag.String("json-proxies", "data/proxies.json", "Path to data/proxies.json")
	refreshHoursFlag := flag.Int("refresh-hours", 1, "Interval in hours to reload and test proxies")
	durationFlag := flag.Int("duration", 0, "Total run duration in minutes (0 for infinite)")
	testLimitFlag := flag.Int("test-limit", 150, "Maximum proxies to test per cycle")
	flag.Parse()

	targetURL := *targetURLFlag
	if *channelFlag != "" {
		channel := strings.TrimPrefix(*channelFlag, "https://www.twitch.tv/")
		channel = strings.TrimPrefix(channel, "https://twitch.tv/")
		channel = strings.Trim(channel, "/")
		targetURL = fmt.Sprintf("https://www.twitch.tv/%s", channel)
	}

	fmt.Println("==================================================================")
	fmt.Println("⚡ GO PROXY POOL MANAGER & TRAFFIC ENGINE")
	fmt.Printf("   Target URL:       %s\n", targetURL)
	fmt.Printf("   Workers:          %d\n", *workersFlag)
	fmt.Printf("   Refresh Interval: Every %d hour(s)\n", *refreshHoursFlag)
	if *durationFlag > 0 {
		fmt.Printf("   Duration:         %d minutes\n", *durationFlag)
	} else {
		fmt.Printf("   Duration:         Continuous (Press Ctrl+C to exit)\n")
	}
	fmt.Println("==================================================================")

	// Resolve file paths
	txtFile := *proxyTxtFlag
	if _, err := os.Stat(txtFile); os.IsNotExist(err) {
		txtFile = filepath.Join("..", "proxies.txt")
	}
	jsonFile := *proxyJSONFlag
	if _, err := os.Stat(jsonFile); os.IsNotExist(err) {
		jsonFile = filepath.Join("..", "data", "proxies.json")
	}

	// 1. Initial proxy harvest and health verification
	rawList := fetchPublicProxies(txtFile, jsonFile)
	if len(rawList) == 0 {
		fmt.Println("⚠️  No proxies found in files. Please run 'python scripts/scraper.py' first.")
	} else {
		testAndFilterProxies(rawList, targetURL, *testLimitFlag)
	}

	// 2. Setup context for graceful shutdown
	ctx, cancel := context.WithCancel(context.Background())
	if *durationFlag > 0 {
		ctx, cancel = context.WithTimeout(ctx, time.Duration(*durationFlag)*time.Minute)
	}

	var wg sync.WaitGroup
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)

	// 3. Launch worker fleet
	fmt.Printf("[System] Launching %d concurrent worker goroutines...\n", *workersFlag)
	for i := 1; i <= *workersFlag; i++ {
		wg.Add(1)
		go runTrafficSimulation(ctx, i, targetURL, &wg)
		time.Sleep(30 * time.Millisecond)
	}

	// 4. Background recurring scheduler: Reload and re-test proxies periodically
	if *refreshHoursFlag > 0 {
		ticker := time.NewTicker(time.Duration(*refreshHoursFlag) * time.Hour)
		go func() {
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					fmt.Printf("\n[Scheduler] %d hour(s) elapsed. Reloading and verifying proxies...\n", *refreshHoursFlag)
					freshList := fetchPublicProxies(txtFile, jsonFile)
					if len(freshList) > 0 {
						testAndFilterProxies(freshList, targetURL, *testLimitFlag)
					}
				}
			}
		}()
	}

	// 5. Wait for shutdown signal
	select {
	case <-sigChan:
		fmt.Println("\n🛑 Stop signal received. Shutting down worker fleet...")
	case <-ctx.Done():
		fmt.Println("\n⏱️ Configured run duration reached. Terminating...")
	}

	cancel()
	wg.Wait()
	fmt.Println("✅ All worker routines successfully closed.")
}
